code --install-extension alex-pex.theme-darkula
code --install-extension bceskavich.theme-dracula-at-night
code --install-extension beardedbear.beardedtheme
code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc
code --install-extension dbaeumer.vscode-eslint
code --install-extension devsense.composer-php-vscode
code --install-extension devsense.phptools-vscode
code --install-extension devsense.profiler-php-vscode
code --install-extension dracula-theme.theme-dracula
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension miguelsolorio.min-theme
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension pkief.material-icon-theme
code --install-extension prisma.prisma
code --install-extension sainoba.px-to-rem
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension teabyii.ayu
